### ISSUE TITLE
API image get returns 500 instead of 404

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/image-service#97] opened 2019-10-17 21:49 UTC
**Steps to reproduce:**
```
REDBACK-GS:~ mol109$ wget -O image.png "https://images-dev.ala.org.au/image/3c79e6a6-3861-4a9c-975b-a32b84bc5ca9" --header="Accept: image/jpeg" 
```

**Expected**
404 code

**Actual**
500 code

**Comment by ansell** [comment] 2019-10-17 21:55
HTTP 500 is a legitimate response code for an invalid URL structure. Using a GUID instead of "ABC" returns the expected dummy image as designed. Closing this as not an issue.

**Comment by javier-molina** [comment] 2019-10-17 23:30
Thanks @ansell for the point on ABC not being a valid GUID.

I tested your scenario and I'm still getting 500, so I'm reopening not to mention that @djtfmartin had already comfirmed this as a bug: https://github.com/AtlasOfLivingAustralia/cab/issues/13#issuecomment-542858565

**Comment by ansell** [comment] 2019-10-17 23:33
This bug should not be a reason to avoid releasing image-service-1.0.11 as HTTP 404 is returned if you test with properly structured GUIDs. `ABC` isn't ever going to be recognised as an identifier for an image as the GUID specification is quite distinct about the syntax.

Assigning priority-low so it doesn't disrupt the release schedule.

**Comment by ansell** [comment] 2019-10-18 03:03
There was one change this morning, deploying 1.0.11. Your testing over the past few days was on an unknown 1.0.11-SNAPSHOT version unfortunately which invalidates it in terms of CAB. 

Since deploying 1.0.11 I am also getting HTTP 500 for that call

**Comment by djtfmartin** [comment] 2019-10-18 12:39
This is fixed on the develop branch.

**Comment by ansell** [comment] 2019-11-01 01:28
This is working for me on images-dev.

**Closed by ansell** 2019-11-01 01:28 UTC
Labels: bug, priority-low
